#!/bin/bash

[ -d ~/.scrots/ ] && continue || mkdir ~/.scrots/

scrot -q 100 -s ~/.scrots/image.png
xclip -sel clipboard -t image/png -i image.png
mv ~/.scrots/image.png ~/.scrots/`date +%Y-%m-%d_%T`.png
