#!/bin/bash
#import script for screenshotting

[ -d $HOME/.scrots/ ] && : || mkdir $HOME/.scrots

escrotum -C -s ~/.scrots/image.png
xclip -selection clipboard -t image/png -o > ~/.scrots/`date '+%Y-%m-%d_%T'`.png
notify-send -t 3000 "<b>scrotplus:</b> $(command ls ~/.scrots | tail -n 1) saved to clipboard and file."
